backend:
  # GANTI DARI 'github' MENJADI 'git-gateway'
  name: git-gateway 
  # URL tempat identitas Netlify Anda berada
  identity_url: "https://tescm.netlify.app/.netlify/identity" 
  # repo dan branch tetap diperlukan untuk git-gateway
  repo: risqitunggal/Risqi 
  branch: main 

publish_mode: editorial_workflow 

media_folder: "gambar/berita" 
public_folder: "/gambar/berita" 

collections:
  - name: "berita" 
    label: "Berita & Artikel"
    folder: "_berita"
    create: true 
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" 
    fields:
      - {label: "Judul", name: "title", widget: "string"}
      - {label: "Tanggal Posting", name: "date", widget: "datetime"}
      - {label: "Gambar Utama", name: "image", widget: "image"}
      - {label: "Ringkasan Singkat", name: "summary", widget: "text"}
      - {label: "Konten Berita", name: "body", widget: "markdown"}